# Generated by Django 3.2.20 on 2023-08-11 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='사용자 아이디')),
                ('password', models.CharField(max_length=20, verbose_name='비밀번호')),
                ('nickname', models.CharField(max_length=20, verbose_name='닉네임')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_number', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.user')),
            ],
        ),
    ]
